export const SIEMENS_HEADER = `
;----------------------------------------
; Generated by AI Siemens CNC Programmer
; Controller: SINUMERIK 840D sl
;----------------------------------------
G17 G90 G54 G71
G64 P0.01
COMPON
SOFT
`;

export const SIEMENS_FOOTER = `
M30
;----------------------------------------
; End of Program
;----------------------------------------
`;
